# Basic configuration for MyFirstCIProject
project:
  name: MyFirstCIProject
  version: 0.1.0
  description: A simple project to learn CI/CD

# Some example configuration settings
settings:
  debug_mode: false
  max_users: 100

# List of maintainers
maintainers:
  - name: Nasim Yousefi
    email: nasim.yousefi05@gmail.com

# Dependencies (example)
# dependencies:
